# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    queue: background
    schedule: every hour at minute 12

  clear_expired_one_time_passwords:
    class: ClearExpiredOneTimePasswordsJob
    queue: background
    schedule: every hour

  uptime_ping:
    class: UptimePingJob
    queue: uptime
    schedule: every minute

  refresh_idv_data:
    class: RefreshIdvDataJob
    queue: background
    schedule: every 10 minutes
  
  sync_airtable_data:
    class: AirtableSyncJob
    queue: background
    schedule: every 10 minutes

  refresh_recommendations:
    class: RecommenderJob
    queue: recommendation
    schedule: every hour
